[General]

# font
fontFamily=Terminus
barFontSize=14
passwordFontSize=14

# color
backgroundColor=#222222
barBackgroundColor=#222222
barTextColor=#bbbbbb
normalBorderColor=#444444
selectedBorderColor=#005577
selectedBackgroundColor=#005577
selectedTextColor=#eeeeee
inputBackgroundColor=#111111
inputTextColor=#bbbbbb
placeholderColor=#888887

# bar
barHeight=18
showDate=true
showTime=true

# date
dateFormat=dd-MM-yyyy

# clock
timeFormat=HH:mm

# session
showSessionTag=true
sessionTagText=dwm-6.4

# password field
passwordCharacter=*
passwordAllowEmpty=false
fieldWidth=220
fieldPadding=8

# wallpaper
wallpaperPath=

# set mode: crop, fit, stretch, tile
wallpaperFillMode=crop

# opacity
wallpaperOverlayOpacity=0.35

# behavior
showUsersByDefault=false
showSessionsByDefault=false
