[General]
background=
BackgroundColor=#0C0E0C
PanelColor=#222222
FieldColor=#191919
BorderColor=#444444
FgColor=#cccccc
FgColorBright=#ffffff
AccentColor=#808080
FontFamily=Terminus
FontSize=11
TagCount=9
